markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - vespaapps_index.json

defaults:
  -
    scope:
      path  : ""
    values:
      index : true

search:
  namespace: "vespaapps"
  doc_type: "doc"
  do_feed  : true
  do_index_removal_before_feed: false
  feed_endpoints:
    # vespacloud-docsearch // aws // us-east-1c
    - url: https://b671e1db.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch // gcp // us-central1-f
    - url: https://a341952a.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch // aws // us-west-1a
    - url: https://ed053d52.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch // aws (enclave) // us-west-1a
    - url: https://f10d3607.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch // gcp (enclave) // us-central1-f
    - url: https://ac5f3559.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
