[project]
name = "visual-retrieval-colpali"
version = "0.1.0"
description = "Visual retrieval with ColPali"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }
dependencies = [
    "python-fasthtml",
    "huggingface-hub",
    "pyvespa>=0.50.0",
    "vespacli",
    "torch",
    "vidore-benchmark[interpretability]>=4.0.0,<5.0.0",
    "colpali-engine>=0.3.2,<0.4.0",
    "einops",
    "pypdf",
    "setuptools",
    "python-dotenv",
    "shad4fast>=1.2.1",
]

# dev-dependencies
[project.optional-dependencies]
dev = [
    "ruff",
    "python-dotenv",
    "huggingface_hub[cli]"
]
feed = [
    "ipykernel",
    "jupytext",
    "pydantic",
    "beautifulsoup4",
    "pdf2image",
    "google-generativeai"
]